export type TranslationTree = {
  [key: string]: string | TranslationTree;
};

export const languageOverlays: Record<string, TranslationTree> = {
  as: {
    tabs: {
      home: 'ঘৰ',
      services: 'সেৱা',
      assistant: 'সহায়ক',
      community: 'সম্প্ৰদায়',
      help: 'সহায়',
    },
    common: {
      search: 'সন্ধান',
      call: 'কল',
      directions: 'দিশ',
      verified: 'যাচাইকৃত',
      save: 'সংৰক্ষণ',
      saved: 'সংৰক্ষিত',
      all: 'সকলো',
      signIn: 'চাইন ইন',
      signOut: 'চাইন আউট',
      username: 'ব্যৱহাৰকাৰী নাম',
      password: 'পাছৱৰ্ড',
      close: 'বন্ধ',
    },
    home: {
      heroKicker: 'শিলিগুৰিত আৰম্ভ',
      heroTitle: 'যত্ন, সেৱা আৰু অনুসৰণৰ বাবে এটা সহায়ক স্তৰ।',
      heroBody: 'যাচাইকৃত স্থানীয় প্ৰদানকাৰীৰে আৰম্ভ কৰক, টাইপ কৰাৰ সলনি কল কৰক, প্ৰমাণ সংৰক্ষণ কৰক আৰু দূৰত থকা পৰিয়ালক লগত ৰাখক।',
      heroPrimary: 'যাচাইকৃত সহায় বিচাৰক',
      heroSecondary: 'কলবেক অনুৰোধ',
      signalCity: 'আৰম্ভ চহৰ: শিলিগুৰি',
      signalVerified: 'উৎস-সংযুক্ত',
      signalCaregiver: 'যত্নদাতাৰ বাবে সাজু',
      mobileNeedTitle: 'আজি আপোনাক কি লাগে?',
      mobileServiceTitle: 'যত্ন বিচাৰক',
      mobileServiceBody: 'ডাক্টৰ, যাতায়াত আৰু বৃদ্ধ সহায়।',
      mobileCommunityTitle: 'স্থানীয়ক সোধক',
      mobileCommunityBody: 'নিকটৱৰ্তী শিলিগুৰি পৰিয়ালক সোধক।',
      mobileHelpTitle: 'জৰুৰী সহায় লাগেনে?',
      mobileHelpBody: 'Saathi সহায় ডেস্কৰ পৰা কল বা কলবেক অনুৰোধ কৰক।',
      browseCategories: 'বিভাগ চাওক',
      topRated: 'আপোনাৰ ওচৰত শীৰ্ষ ৰেটেড',
      seeAll: 'সকলো চাওক',
      scaleTitle: 'শিলিগুৰি প্ৰথম প্ৰমাণ, সীমা নহয়',
      scaleBody: 'ইণ্টাৰফেচটো চহৰ-সচেতন, সেয়ে একে বিশ্বাস ব্যৱস্থা স্থানীয় প্ৰসংগ নেহেৰুৱাকৈ আন ভাৰতীয় চহৰলৈ বিস্তাৰ কৰিব পাৰি।',
      myCalendar: 'মোৰ কেলেণ্ডাৰ',
      connectors: 'সংযোগ',
      connectorsCaption: 'Saathi কি সংযোগ কৰিব পাৰে চাওক',
    },
    categories: {
      elder_home: 'বৃদ্ধ যত্ন আৰু ঘৰ',
      doctor: 'ডাক্টৰ',
      hospital: 'হাস্পতাল',
      medical_shop: 'ঔষধৰ দোকান',
      travel_agent: 'যাত্ৰা আৰু পৰিবহন',
      daily_service: 'দৈনিক আৰু নাগৰিক সহায়',
    },
    services: {
      title: 'সেৱা',
      searchPlaceholder: 'Saathi-ৰ তালিকাভুক্ত সেৱা সন্ধান কৰক...',
      favorites: 'প্ৰিয়',
      recentlyViewed: 'শেহতীয়াকৈ চোৱা',
      trustChecklist: 'বিশ্বাস তালিকা',
      sourceLinked: 'উৎস লিংক',
      callFirst: 'যোৱাৰ আগতে কল কৰক',
      viewSource: 'উৎস চাওক',
      contactActions: 'যোগাযোগ কাৰ্য',
    },
    help: {
      title: '২৪/৭ হেল্পলাইন',
      callNow: 'এতিয়াই হেল্পলাইনত কল কৰক',
      requestCallback: 'কলবেক অনুৰোধ',
      languages: 'হিন্দী আৰু ইংৰাজীত উপলব্ধ',
    },
    auth: {
      welcome: 'Saathi লৈ স্বাগতম',
      signInOnly: 'আপোনাৰ একাউণ্টত চাইন ইন কৰক',
      createAccountOnly: 'আপোনাৰ একাউণ্ট সৃষ্টি কৰক',
      fullName: 'সম্পূৰ্ণ নাম',
      identifier: 'ব্যৱহাৰকাৰী নাম বা ফোন নম্বৰ',
      identifierPlaceholder: 'Aadit_J বা +91 98765 43210',
      createAccount: 'একাউণ্ট সৃষ্টি কৰক',
      haveAccount: 'মোৰ ইতিমধ্যে একাউণ্ট আছে',
      needAccount: 'নতুন একাউণ্ট সৃষ্টি কৰক',
    },
  },
  bn: {
    tabs: {
      home: 'হোম',
      services: 'সেবা',
      assistant: 'সহায়ক',
      community: 'কমিউনিটি',
      help: 'সাহায্য',
    },
    common: {
      search: 'খুঁজুন',
      call: 'কল',
      directions: 'দিকনির্দেশ',
      verified: 'যাচাইকৃত',
      save: 'সংরক্ষণ',
      saved: 'সংরক্ষিত',
      all: 'সব',
      signIn: 'সাইন ইন',
      signOut: 'সাইন আউট',
      username: 'ইউজারনেম',
      password: 'পাসওয়ার্ড',
      close: 'বন্ধ',
    },
    home: {
      heroKicker: 'শিলিগুড়িতে শুরু',
      heroTitle: 'যত্ন, সেবা এবং ফলো-আপের জন্য এক সঙ্গী স্তর।',
      heroBody: 'যাচাইকৃত স্থানীয় পরিষেবা দিয়ে শুরু করুন, টাইপ করার বদলে কল করুন, প্রমাণ সংরক্ষণ করুন এবং দূরের পরিবারকে সঙ্গে রাখুন।',
      heroPrimary: 'যাচাইকৃত সাহায্য খুঁজুন',
      heroSecondary: 'কলব্যাক চাইুন',
      signalCity: 'লঞ্চ শহর: শিলিগুড়ি',
      signalVerified: 'উৎস-সংযুক্ত',
      signalCaregiver: 'কেয়ারগিভার-প্রস্তুত',
      mobileNeedTitle: 'আজ আপনার কী দরকার?',
      mobileServiceTitle: 'যত্ন খুঁজুন',
      mobileServiceBody: 'ডাক্তার, যাতায়াত এবং প্রবীণ সহায়তা।',
      mobileCommunityTitle: 'স্থানীয়দের জিজ্ঞাসা করুন',
      mobileCommunityBody: 'কাছের শিলিগুড়ি পরিবারগুলিকে জিজ্ঞাসা করুন।',
      mobileHelpTitle: 'জরুরি সাহায্য দরকার?',
      mobileHelpBody: 'Saathi হেল্প ডেস্ক থেকে কল বা কলব্যাক চাইুন।',
      browseCategories: 'বিভাগ দেখুন',
      topRated: 'আপনার কাছে শীর্ষ রেটেড',
      seeAll: 'সব দেখুন',
      scaleTitle: 'শিলিগুড়ি প্রথম প্রমাণ, সীমা নয়',
      scaleBody: 'ইন্টারফেসটি শহর-সচেতন, তাই একই বিশ্বাস ব্যবস্থা স্থানীয় প্রসঙ্গ না হারিয়ে অন্য ভারতীয় শহরে যেতে পারে।',
      myCalendar: 'আমার ক্যালেন্ডার',
      connectors: 'সংযোগ',
      connectorsCaption: 'Saathi কী সংযুক্ত করতে পারে দেখুন',
    },
    categories: {
      elder_home: 'প্রবীণ যত্ন ও বাড়ি',
      doctor: 'ডাক্তার',
      hospital: 'হাসপাতাল',
      medical_shop: 'ওষুধের দোকান',
      travel_agent: 'ভ্রমণ ও পরিবহন',
      daily_service: 'দৈনন্দিন ও নাগরিক সহায়তা',
    },
    services: {
      title: 'সেবা',
      searchPlaceholder: 'Saathi-র তালিকাভুক্ত সেবা খুঁজুন...',
      favorites: 'প্রিয়',
      recentlyViewed: 'সম্প্রতি দেখা',
      trustChecklist: 'বিশ্বাসের তালিকা',
      sourceLinked: 'উৎস লিংক',
      callFirst: 'যাওয়ার আগে কল করুন',
      viewSource: 'উৎস দেখুন',
      contactActions: 'যোগাযোগ কাজ',
    },
    help: {
      title: '২৪/৭ হেল্পলাইন',
      callNow: 'এখনই হেল্পলাইনে কল করুন',
      requestCallback: 'কলব্যাক চাইুন',
      languages: 'হিন্দি ও ইংরেজিতে উপলব্ধ',
    },
    auth: {
      welcome: 'Saathi-তে স্বাগতম',
      signInOnly: 'আপনার অ্যাকাউন্টে সাইন ইন করুন',
      createAccountOnly: 'আপনার অ্যাকাউন্ট তৈরি করুন',
      fullName: 'পুরো নাম',
      identifier: 'ইউজারনেম বা ফোন নম্বর',
      identifierPlaceholder: 'Aadit_J অথবা +91 98765 43210',
      createAccount: 'অ্যাকাউন্ট তৈরি করুন',
      haveAccount: 'আমার ইতিমধ্যে অ্যাকাউন্ট আছে',
      needAccount: 'নতুন অ্যাকাউন্ট তৈরি করুন',
    },
  },
  gu: {
    tabs: { home: 'હોમ', services: 'સેવાઓ', assistant: 'સહાયક', community: 'સમુદાય', help: 'મદદ' },
    common: {
      search: 'શોધો',
      call: 'કૉલ',
      directions: 'દિશાઓ',
      verified: 'ચકાસાયેલ',
      save: 'સાચવો',
      saved: 'સાચવ્યું',
      all: 'બધું',
      signIn: 'સાઇન ઇન',
      signOut: 'સાઇન આઉટ',
      username: 'યૂઝરનેમ',
      password: 'પાસવર્ડ',
      close: 'બંધ',
    },
    home: {
      heroKicker: 'સિલિગુરીમાં શરૂઆત',
      heroTitle: 'કેર, સેવાઓ અને ફોલો-અપ માટે એક સાથી સ્તર.',
      heroBody: 'ચકાસાયેલા સ્થાનિક પ્રદાતાઓથી શરૂ કરો, ટાઇપ કરવાને બદલે કૉલ કરો, પુરાવો સાચવો અને દૂરના પરિવારને જોડાયેલા રાખો.',
      heroPrimary: 'ચકાસાયેલ મદદ શોધો',
      heroSecondary: 'કોલબેક માગો',
      signalCity: 'લૉન્ચ શહેર: સિલિગુરી',
      signalVerified: 'સ્રોત-લિંકડ',
      signalCaregiver: 'કેરગિવર-તૈયાર',
      mobileNeedTitle: 'આજે તમને શું જોઈએ?',
      mobileServiceTitle: 'કેર શોધો',
      mobileServiceBody: 'ડૉક્ટર, રાઇડ અને વૃદ્ધ મદદ.',
      mobileCommunityTitle: 'સ્થાનિકોને પૂછો',
      mobileCommunityBody: 'નજીકના સિલિગુરી પરિવારોને પૂછો.',
      mobileHelpTitle: 'તાત્કાલિક મદદ જોઈએ?',
      mobileHelpBody: 'Saathi હેલ્પ ડેસ્કથી કૉલ અથવા કોલબેક માગો.',
      browseCategories: 'શ્રેણીઓ જુઓ',
      topRated: 'તમારી નજીક શ્રેષ્ઠ રેટેડ',
      seeAll: 'બધું જુઓ',
      scaleTitle: 'સિલિગુરી પ્રથમ પુરાવો છે, સીમા નહીં',
      scaleBody: 'ઇન્ટરફેસ શહેર-જાગૃત છે જેથી એ જ વિશ્વાસ સિસ્ટમ સ્થાનિક સંદર્ભ ગુમાવ્યા વિના બીજા ભારતીય શહેરોમાં જઈ શકે.',
      myCalendar: 'મારું કેલેન્ડર',
      connectors: 'કનેક્શન',
      connectorsCaption: 'Saathi શું જોડે છે તે જુઓ',
    },
    categories: {
      elder_home: 'વૃદ્ધ સંભાળ અને ઘર',
      doctor: 'ડૉક્ટર',
      hospital: 'હૉસ્પિટલ',
      medical_shop: 'મેડિકલ દુકાનો',
      travel_agent: 'મુસાફરી અને પરિવહન',
      daily_service: 'દૈનિક અને નાગરિક મદદ',
    },
    services: {
      title: 'સેવાઓ',
      searchPlaceholder: 'Saathiની સૂચિબદ્ધ સેવાઓ શોધો...',
      favorites: 'પ્રિય',
      recentlyViewed: 'હમણાં જોયેલું',
      trustChecklist: 'વિશ્વાસ ચેકલિસ્ટ',
      sourceLinked: 'સ્રોત લિંક',
      callFirst: 'જતાં પહેલાં કૉલ કરો',
      viewSource: 'સ્રોત જુઓ',
      contactActions: 'સંપર્ક ક્રિયાઓ',
    },
    help: { title: '24/7 હેલ્પલાઇન', callNow: 'હમણાં હેલ્પલાઇન પર કૉલ કરો', requestCallback: 'કોલબેક માગો', languages: 'હિન્દી અને અંગ્રેજીમાં ઉપલબ્ધ' },
    auth: {
      welcome: 'Saathiમાં સ્વાગત છે',
      signInOnly: 'તમારા ખાતામાં સાઇન ઇન કરો',
      createAccountOnly: 'તમારું ખાતું બનાવો',
      fullName: 'પૂરું નામ',
      identifier: 'યૂઝરનેમ અથવા ફોન નંબર',
      identifierPlaceholder: 'Aadit_J અથવા +91 98765 43210',
      createAccount: 'ખાતું બનાવો',
      haveAccount: 'મારું પહેલેથી ખાતું છે',
      needAccount: 'નવું ખાતું બનાવો',
    },
  },
  kn: {
    tabs: { home: 'ಮುಖಪುಟ', services: 'ಸೇವೆಗಳು', assistant: 'ಸಹಾಯಕ', community: 'ಸಮುದಾಯ', help: 'ಸಹಾಯ' },
    common: {
      search: 'ಹುಡುಕಿ',
      call: 'ಕರೆ',
      directions: 'ದಿಕ್ಕುಗಳು',
      verified: 'ಪರಿಶೀಲಿತ',
      save: 'ಉಳಿಸಿ',
      saved: 'ಉಳಿಸಲಾಗಿದೆ',
      all: 'ಎಲ್ಲ',
      signIn: 'ಸೈನ್ ಇನ್',
      signOut: 'ಸೈನ್ ಔಟ್',
      username: 'ಬಳಕೆದಾರ ಹೆಸರು',
      password: 'ಪಾಸ್‌ವರ್ಡ್',
      close: 'ಮುಚ್ಚಿ',
    },
    home: {
      heroKicker: 'ಸಿಲಿಗುರಿಯಲ್ಲಿ ಆರಂಭ',
      heroTitle: 'ಪಾಲನೆ, ಸೇವೆಗಳು ಮತ್ತು ಫಾಲೋ-ಅಪ್‌ಗಾಗಿ ಒಂದು ಸಂಗಾತಿ ಪದರ.',
      heroBody: 'ಪರಿಶೀಲಿತ ಸ್ಥಳೀಯ ಸೇವೆಗಳಿಂದ ಆರಂಭಿಸಿ, ಟೈಪ್ ಮಾಡುವ ಬದಲು ಕರೆ ಮಾಡಿ, ಸಾಕ್ಷ್ಯ ಉಳಿಸಿ ಮತ್ತು ದೂರದ ಕುಟುಂಬವನ್ನು ಸಂಪರ್ಕದಲ್ಲಿರಿಸಿ.',
      heroPrimary: 'ಪರಿಶೀಲಿತ ಸಹಾಯ ಹುಡುಕಿ',
      heroSecondary: 'ಕಾಲ್‌ಬ್ಯಾಕ್ ಕೇಳಿ',
      signalCity: 'ಲಾಂಚ್ ನಗರ: ಸಿಲಿಗುರಿ',
      signalVerified: 'ಮೂಲ-ಲಿಂಕ್',
      signalCaregiver: 'ಪಾಲಕ-ಸಿದ್ಧ',
      mobileNeedTitle: 'ಇಂದು ನಿಮಗೆ ಏನು ಬೇಕು?',
      mobileServiceTitle: 'ಪಾಲನೆ ಹುಡುಕಿ',
      mobileServiceBody: 'ವೈದ್ಯರು, ಪ್ರಯಾಣ ಮತ್ತು ಹಿರಿಯರ ಸಹಾಯ.',
      mobileCommunityTitle: 'ಸ್ಥಳೀಯರನ್ನು ಕೇಳಿ',
      mobileCommunityBody: 'ಹತ್ತಿರದ ಸಿಲಿಗುರಿ ಕುಟುಂಬಗಳನ್ನು ಕೇಳಿ.',
      mobileHelpTitle: 'ತುರ್ತು ಸಹಾಯ ಬೇಕೇ?',
      mobileHelpBody: 'Saathi ಸಹಾಯ ಡೆಸ್ಕ್‌ನಿಂದ ಕರೆ ಅಥವಾ ಕಾಲ್‌ಬ್ಯಾಕ್ ಕೇಳಿ.',
      browseCategories: 'ವರ್ಗಗಳನ್ನು ನೋಡಿ',
      topRated: 'ನಿಮ್ಮ ಹತ್ತಿರ ಉನ್ನತ ರೇಟಿಂಗ್',
      seeAll: 'ಎಲ್ಲ ನೋಡಿ',
      scaleTitle: 'ಸಿಲಿಗುರಿ ಮೊದಲ ಸಾಕ್ಷ್ಯ, ಗಡಿ ಅಲ್ಲ',
      scaleBody: 'ಇಂಟರ್‌ಫೇಸ್ ನಗರ-ಜಾಗೃತವಾಗಿದ್ದು, ಅದೇ ವಿಶ್ವಾಸ ವ್ಯವಸ್ಥೆ ಸ್ಥಳೀಯ ಸಂದರ್ಭ ಕಳೆದುಕೊಳ್ಳದೆ ಬೇರೆ ನಗರಗಳಿಗೆ ವಿಸ್ತರಿಸಬಹುದು.',
      myCalendar: 'ನನ್ನ ಕ್ಯಾಲೆಂಡರ್',
      connectors: 'ಸಂಪರ್ಕಗಳು',
      connectorsCaption: 'Saathi ಏನು ಸಂಪರ್ಕಿಸಬಹುದು ನೋಡಿ',
    },
    categories: {
      elder_home: 'ಹಿರಿಯರ ಪಾಲನೆ ಮತ್ತು ಮನೆಗಳು',
      doctor: 'ವೈದ್ಯರು',
      hospital: 'ಆಸ್ಪತ್ರೆಗಳು',
      medical_shop: 'ಔಷಧ ಅಂಗಡಿಗಳು',
      travel_agent: 'ಪ್ರಯಾಣ ಮತ್ತು ಸಾರಿಗೆ',
      daily_service: 'ದೈನಂದಿನ ಮತ್ತು ನಾಗರಿಕ ಸಹಾಯ',
    },
    services: {
      title: 'ಸೇವೆಗಳು',
      searchPlaceholder: 'Saathi ಪಟ್ಟಿ ಮಾಡಿದ ಸೇವೆಗಳನ್ನು ಹುಡುಕಿ...',
      favorites: 'ಮೆಚ್ಚಿನವು',
      recentlyViewed: 'ಇತ್ತೀಚೆಗೆ ನೋಡಿದವು',
      trustChecklist: 'ವಿಶ್ವಾಸ ಪರಿಶೀಲನಾ ಪಟ್ಟಿ',
      sourceLinked: 'ಮೂಲ ಲಿಂಕ್',
      callFirst: 'ಭೇಟಿಗೆ ಮುನ್ನ ಕರೆ ಮಾಡಿ',
      viewSource: 'ಮೂಲ ನೋಡಿ',
      contactActions: 'ಸಂಪರ್ಕ ಕ್ರಮಗಳು',
    },
    help: { title: '24/7 ಸಹಾಯವಾಣಿ', callNow: 'ಈಗ ಸಹಾಯವಾಣಿಗೆ ಕರೆ ಮಾಡಿ', requestCallback: 'ಕಾಲ್‌ಬ್ಯಾಕ್ ಕೇಳಿ', languages: 'ಹಿಂದಿ ಮತ್ತು ಇಂಗ್ಲಿಷ್‌ನಲ್ಲಿ ಲಭ್ಯ' },
    auth: {
      welcome: 'Saathiಗೆ ಸ್ವಾಗತ',
      signInOnly: 'ನಿಮ್ಮ ಖಾತೆಗೆ ಸೈನ್ ಇನ್ ಮಾಡಿ',
      createAccountOnly: 'ನಿಮ್ಮ ಖಾತೆ ರಚಿಸಿ',
      fullName: 'ಪೂರ್ಣ ಹೆಸರು',
      identifier: 'ಬಳಕೆದಾರ ಹೆಸರು ಅಥವಾ ಫೋನ್ ಸಂಖ್ಯೆ',
      identifierPlaceholder: 'Aadit_J ಅಥವಾ +91 98765 43210',
      createAccount: 'ಖಾತೆ ರಚಿಸಿ',
      haveAccount: 'ನನಗೆ ಈಗಾಗಲೇ ಖಾತೆ ಇದೆ',
      needAccount: 'ಹೊಸ ಖಾತೆ ರಚಿಸಿ',
    },
  },
  ml: {
    tabs: { home: 'ഹോം', services: 'സേവനങ്ങൾ', assistant: 'സഹായി', community: 'കമ്മ്യൂണിറ്റി', help: 'സഹായം' },
    common: {
      search: 'തിരയുക',
      call: 'വിളിക്കുക',
      directions: 'ദിശകൾ',
      verified: 'പരിശോധിച്ചത്',
      save: 'സേവ്',
      saved: 'സേവ് ചെയ്തു',
      all: 'എല്ലാം',
      signIn: 'സൈൻ ഇൻ',
      signOut: 'സൈൻ ഔട്ട്',
      username: 'യൂസർനേം',
      password: 'പാസ്‌വേഡ്',
      close: 'അടയ്ക്കുക',
    },
    home: {
      heroKicker: 'സിലിഗുരിയിൽ ആരംഭം',
      heroTitle: 'പരിചരണം, സേവനങ്ങൾ, ഫോളോ-അപ്പ് എന്നിവയ്ക്കുള്ള ഒരു കൂട്ടാളി പാളി.',
      heroBody: 'പരിശോധിച്ച പ്രാദേശിക സേവനദാതാക്കളിൽ നിന്ന് ആരംഭിക്കുക, ടൈപ്പ് ചെയ്യുന്നതിനുപകരം വിളിക്കുക, തെളിവ് സേവ് ചെയ്യുക, ദൂരെയുള്ള കുടുംബത്തെ ബന്ധിപ്പിച്ച് നിലനിർത്തുക.',
      heroPrimary: 'പരിശോധിച്ച സഹായം കണ്ടെത്തുക',
      heroSecondary: 'കാൾബാക്ക് അഭ്യർത്ഥിക്കുക',
      signalCity: 'ലോഞ്ച് നഗരം: സിലിഗുരി',
      signalVerified: 'ഉറവിട-ലിങ്ക്',
      signalCaregiver: 'കെയർഗിവർ-തയ്യാർ',
      mobileNeedTitle: 'ഇന്ന് നിങ്ങൾക്ക് എന്ത് വേണം?',
      mobileServiceTitle: 'പരിചരണം കണ്ടെത്തുക',
      mobileServiceBody: 'ഡോക്ടർമാർ, യാത്ര, മുതിർന്നവർക്കുള്ള സഹായം.',
      mobileCommunityTitle: 'പ്രാദേശികരോട് ചോദിക്കുക',
      mobileCommunityBody: 'സമീപത്തെ സിലിഗുരി കുടുംബങ്ങളോട് ചോദിക്കുക.',
      mobileHelpTitle: 'അടിയന്തിര സഹായം വേണോ?',
      mobileHelpBody: 'Saathi ഹെൽപ്പ് ഡെസ്കിൽ നിന്ന് വിളി അല്ലെങ്കിൽ കാൾബാക്ക് അഭ്യർത്ഥിക്കുക.',
      browseCategories: 'വിഭാഗങ്ങൾ കാണുക',
      topRated: 'നിങ്ങളുടെ സമീപത്തെ മികച്ചവ',
      seeAll: 'എല്ലാം കാണുക',
      scaleTitle: 'സിലിഗുരി ആദ്യ തെളിവാണ്, അതിരല്ല',
      scaleBody: 'ഇന്റർഫേസ് നഗരം മനസ്സിലാക്കുന്നതിനാൽ അതേ വിശ്വാസ സംവിധാനം പ്രാദേശിക പശ്ചാത്തലം നഷ്ടപ്പെടാതെ മറ്റു നഗരങ്ങളിലേക്ക് വ്യാപിക്കാം.',
      myCalendar: 'എന്റെ കലണ്ടർ',
      connectors: 'കണക്ഷനുകൾ',
      connectorsCaption: 'Saathi എന്തെല്ലാം ബന്ധിപ്പിക്കും എന്ന് കാണുക',
    },
    categories: {
      elder_home: 'മുതിർന്നവരുടെ പരിചരണവും വീടുകളും',
      doctor: 'ഡോക്ടർമാർ',
      hospital: 'ആശുപത്രികൾ',
      medical_shop: 'മെഡിക്കൽ ഷോപ്പുകൾ',
      travel_agent: 'യാത്രയും ഗതാഗതവും',
      daily_service: 'ദൈനംദിനവും പൗരസഹായവും',
    },
    services: {
      title: 'സേവനങ്ങൾ',
      searchPlaceholder: 'Saathi ലിസ്റ്റ് ചെയ്ത സേവനങ്ങൾ തിരയുക...',
      favorites: 'പ്രിയപ്പെട്ടവ',
      recentlyViewed: 'സമീപകാലത്ത് കണ്ടത്',
      trustChecklist: 'വിശ്വാസ ചെക്ക്ലിസ്റ്റ്',
      sourceLinked: 'ഉറവിട ലിങ്ക്',
      callFirst: 'സന്ദർശിക്കുന്നതിന് മുമ്പ് വിളിക്കുക',
      viewSource: 'ഉറവിടം കാണുക',
      contactActions: 'കോണ്ടാക്ട് ആക്ഷനുകൾ',
    },
    help: { title: '24/7 ഹെൽപ്പ്ലൈൻ', callNow: 'ഇപ്പോൾ ഹെൽപ്പ്ലൈനിൽ വിളിക്കുക', requestCallback: 'കാൾബാക്ക് അഭ്യർത്ഥിക്കുക', languages: 'ഹിന്ദിയിലും ഇംഗ്ലീഷിലും ലഭ്യം' },
    auth: {
      welcome: 'Saathiയിലേക്ക് സ്വാഗതം',
      signInOnly: 'നിങ്ങളുടെ അക്കൗണ്ടിൽ സൈൻ ഇൻ ചെയ്യുക',
      createAccountOnly: 'നിങ്ങളുടെ അക്കൗണ്ട് സൃഷ്ടിക്കുക',
      fullName: 'പൂർണ്ണ പേര്',
      identifier: 'യൂസർനേം അല്ലെങ്കിൽ ഫോൺ നമ്പർ',
      identifierPlaceholder: 'Aadit_J അല്ലെങ്കിൽ +91 98765 43210',
      createAccount: 'അക്കൗണ്ട് സൃഷ്ടിക്കുക',
      haveAccount: 'എനിക്ക് ഇതിനകം അക്കൗണ്ട് ഉണ്ട്',
      needAccount: 'പുതിയ അക്കൗണ്ട് സൃഷ്ടിക്കുക',
    },
  },
  mr: {
    tabs: { home: 'होम', services: 'सेवा', assistant: 'सहायक', community: 'समुदाय', help: 'मदत' },
    common: {
      search: 'शोधा',
      call: 'कॉल',
      directions: 'दिशा',
      verified: 'सत्यापित',
      save: 'जतन करा',
      saved: 'जतन केले',
      all: 'सर्व',
      signIn: 'साइन इन',
      signOut: 'साइन आउट',
      username: 'युजरनेम',
      password: 'पासवर्ड',
      close: 'बंद',
    },
    home: {
      heroKicker: 'सिलिगुडीमध्ये सुरुवात',
      heroTitle: 'काळजी, सेवा आणि फॉलो-अपसाठी एक साथी स्तर.',
      heroBody: 'सत्यापित स्थानिक प्रदात्यांपासून सुरुवात करा, टाइप करण्याऐवजी कॉल करा, पुरावा जतन करा आणि दूरच्या कुटुंबाला जोडून ठेवा.',
      heroPrimary: 'सत्यापित मदत शोधा',
      heroSecondary: 'कॉलबॅक मागा',
      signalCity: 'लॉन्च शहर: सिलिगुडी',
      signalVerified: 'स्रोत-जोडलेले',
      signalCaregiver: 'केअरगिव्हर-तयार',
      mobileNeedTitle: 'आज तुम्हाला काय हवे आहे?',
      mobileServiceTitle: 'काळजी शोधा',
      mobileServiceBody: 'डॉक्टर, प्रवास आणि ज्येष्ठ मदत.',
      mobileCommunityTitle: 'स्थानिकांना विचारा',
      mobileCommunityBody: 'जवळच्या सिलिगुडी कुटुंबांना विचारा.',
      mobileHelpTitle: 'तातडीची मदत हवी?',
      mobileHelpBody: 'Saathi हेल्प डेस्ककडून कॉल किंवा कॉलबॅक मागा.',
      browseCategories: 'विभाग पहा',
      topRated: 'तुमच्या जवळ सर्वोत्तम रेटेड',
      seeAll: 'सर्व पहा',
      scaleTitle: 'सिलिगुडी पहिला पुरावा आहे, सीमा नाही',
      scaleBody: 'इंटरफेस शहर-जागरूक आहे, त्यामुळे तोच विश्वास प्रणाली स्थानिक संदर्भ न गमावता इतर शहरांत वाढू शकतो.',
      myCalendar: 'माझे कॅलेंडर',
      connectors: 'कनेक्शन',
      connectorsCaption: 'Saathi काय जोडू शकते ते पहा',
    },
    categories: {
      elder_home: 'ज्येष्ठ काळजी आणि घरे',
      doctor: 'डॉक्टर',
      hospital: 'रुग्णालये',
      medical_shop: 'मेडिकल दुकाने',
      travel_agent: 'प्रवास आणि वाहतूक',
      daily_service: 'दैनंदिन आणि नागरी मदत',
    },
    services: {
      title: 'सेवा',
      searchPlaceholder: 'Saathi मधील सूचीबद्ध सेवा शोधा...',
      favorites: 'आवडते',
      recentlyViewed: 'अलीकडे पाहिलेले',
      trustChecklist: 'विश्वास चेकलिस्ट',
      sourceLinked: 'स्रोत लिंक',
      callFirst: 'भेट देण्यापूर्वी कॉल करा',
      viewSource: 'स्रोत पहा',
      contactActions: 'संपर्क कृती',
    },
    help: { title: '24/7 हेल्पलाइन', callNow: 'आता हेल्पलाइनला कॉल करा', requestCallback: 'कॉलबॅक मागा', languages: 'हिंदी आणि इंग्रजीमध्ये उपलब्ध' },
    auth: {
      welcome: 'Saathi मध्ये स्वागत',
      signInOnly: 'तुमच्या खात्यात साइन इन करा',
      createAccountOnly: 'तुमचे खाते तयार करा',
      fullName: 'पूर्ण नाव',
      identifier: 'युजरनेम किंवा फोन नंबर',
      identifierPlaceholder: 'Aadit_J किंवा +91 98765 43210',
      createAccount: 'खाते तयार करा',
      haveAccount: 'माझे आधीच खाते आहे',
      needAccount: 'नवे खाते तयार करा',
    },
  },
  or: {
    tabs: { home: 'ହୋମ', services: 'ସେବା', assistant: 'ସହାୟକ', community: 'ସମୁଦାୟ', help: 'ସହାୟତା' },
    common: {
      search: 'ଖୋଜନ୍ତୁ',
      call: 'କଲ୍',
      directions: 'ଦିଗ',
      verified: 'ଯାଞ୍ଚିତ',
      save: 'ସେଭ୍',
      saved: 'ସେଭ୍ ହେଲା',
      all: 'ସବୁ',
      signIn: 'ସାଇନ୍ ଇନ୍',
      signOut: 'ସାଇନ୍ ଆଉଟ୍',
      username: 'ୟୁଜରନେମ୍',
      password: 'ପାସୱାର୍ଡ',
      close: 'ବନ୍ଦ',
    },
    home: {
      heroKicker: 'ସିଲିଗୁଡ଼ିରେ ଆରମ୍ଭ',
      heroTitle: 'ସେବା, ଯତ୍ନ ଏବଂ ଫଲୋ-ଅପ୍ ପାଇଁ ଏକ ସାଥୀ ସ୍ତର।',
      heroBody: 'ଯାଞ୍ଚିତ ସ୍ଥାନୀୟ ପ୍ରଦାନକାରୀ ସହିତ ଆରମ୍ଭ କରନ୍ତୁ, ଟାଇପ୍ କରିବା ବଦଳରେ କଲ୍ କରନ୍ତୁ, ପ୍ରମାଣ ସେଭ୍ କରନ୍ତୁ ଏବଂ ଦୂରର ପରିବାରକୁ ଲୁପ୍‌ରେ ରଖନ୍ତୁ।',
      heroPrimary: 'ଯାଞ୍ଚିତ ସହାୟତା ଖୋଜନ୍ତୁ',
      heroSecondary: 'କଲବ୍ୟାକ୍ ଅନୁରୋଧ',
      signalCity: 'ଲଞ୍ଚ ସହର: ସିଲିଗୁଡ଼ି',
      signalVerified: 'ସ୍ରୋତ-ଲିଙ୍କ୍',
      signalCaregiver: 'କେୟାରଗିଭର-ପ୍ରସ୍ତୁତ',
      mobileNeedTitle: 'ଆଜି ଆପଣଙ୍କୁ କଣ ଦରକାର?',
      mobileServiceTitle: 'ଯତ୍ନ ଖୋଜନ୍ତୁ',
      mobileServiceBody: 'ଡାକ୍ତର, ଯାତାୟାତ ଏବଂ ବୃଦ୍ଧ ସହାୟତା।',
      mobileCommunityTitle: 'ସ୍ଥାନୀୟଙ୍କୁ ପଚାରନ୍ତୁ',
      mobileCommunityBody: 'ନିକଟର ସିଲିଗୁଡ଼ି ପରିବାରକୁ ପଚାରନ୍ତୁ।',
      mobileHelpTitle: 'ତୁରନ୍ତ ସହାୟତା ଦରକାର?',
      mobileHelpBody: 'Saathi ହେଲ୍ପ ଡେସ୍କରୁ କଲ୍ କିମ୍ବା କଲବ୍ୟାକ୍ ଅନୁରୋଧ କରନ୍ତୁ।',
      browseCategories: 'ଶ୍ରେଣୀ ଦେଖନ୍ତୁ',
      topRated: 'ଆପଣଙ୍କ ନିକଟରେ ଶୀର୍ଷ ରେଟେଡ୍',
      seeAll: 'ସବୁ ଦେଖନ୍ତୁ',
      scaleTitle: 'ସିଲିଗୁଡ଼ି ପ୍ରଥମ ପ୍ରମାଣ, ସୀମା ନୁହେଁ',
      scaleBody: 'ଇଣ୍ଟରଫେସ୍ ସହର-ସଚେତନ, ତେଣୁ ସେହି ଭରସା ପ୍ରଣାଳୀ ସ୍ଥାନୀୟ ପ୍ରସଙ୍ଗ ନହରାଇ ଅନ୍ୟ ସହରକୁ ବଢ଼ିପାରେ।',
      myCalendar: 'ମୋ କ୍ୟାଲେଣ୍ଡର',
      connectors: 'ସଂଯୋଗ',
      connectorsCaption: 'Saathi କଣ ସଂଯୋଗ କରିପାରେ ଦେଖନ୍ତୁ',
    },
    categories: {
      elder_home: 'ବୃଦ୍ଧ ଯତ୍ନ ଓ ଘର',
      doctor: 'ଡାକ୍ତର',
      hospital: 'ହସ୍ପିଟାଲ',
      medical_shop: 'ମେଡିକାଲ୍ ଦୋକାନ',
      travel_agent: 'ଯାତ୍ରା ଓ ପରିବହନ',
      daily_service: 'ଦୈନିକ ଓ ନାଗରିକ ସହାୟତା',
    },
    services: {
      title: 'ସେବା',
      searchPlaceholder: 'Saathiର ତାଲିକାଭୁକ୍ତ ସେବା ଖୋଜନ୍ତୁ...',
      favorites: 'ପସନ୍ଦ',
      recentlyViewed: 'ସମ୍ପ୍ରତି ଦେଖା',
      trustChecklist: 'ଭରସା ଚେକଲିଷ୍ଟ',
      sourceLinked: 'ସ୍ରୋତ ଲିଙ୍କ୍',
      callFirst: 'ଯିବା ପୂର୍ବରୁ କଲ୍ କରନ୍ତୁ',
      viewSource: 'ସ୍ରୋତ ଦେଖନ୍ତୁ',
      contactActions: 'ସମ୍ପର୍କ କାର୍ଯ୍ୟ',
    },
    help: { title: '24/7 ହେଲ୍ପଲାଇନ୍', callNow: 'ଏବେ ହେଲ୍ପଲାଇନକୁ କଲ୍ କରନ୍ତୁ', requestCallback: 'କଲବ୍ୟାକ୍ ଅନୁରୋଧ', languages: 'ହିନ୍ଦୀ ଓ ଇଂରାଜୀରେ ଉପଲବ୍ଧ' },
    auth: {
      welcome: 'Saathiକୁ ସ୍ୱାଗତ',
      signInOnly: 'ଆପଣଙ୍କ ଖାତାରେ ସାଇନ୍ ଇନ୍ କରନ୍ତୁ',
      createAccountOnly: 'ଆପଣଙ୍କ ଖାତା ସୃଷ୍ଟି କରନ୍ତୁ',
      fullName: 'ପୂରା ନାମ',
      identifier: 'ୟୁଜରନେମ୍ କିମ୍ବା ଫୋନ୍ ନମ୍ବର',
      identifierPlaceholder: 'Aadit_J କିମ୍ବା +91 98765 43210',
      createAccount: 'ଖାତା ସୃଷ୍ଟି କରନ୍ତୁ',
      haveAccount: 'ମୋର ଖାତା ପୂର୍ବରୁ ଅଛି',
      needAccount: 'ନୂଆ ଖାତା ସୃଷ୍ଟି କରନ୍ତୁ',
    },
  },
  pa: {
    tabs: { home: 'ਹੋਮ', services: 'ਸੇਵਾਵਾਂ', assistant: 'ਸਹਾਇਕ', community: 'ਕਮਿਊਨਿਟੀ', help: 'ਮਦਦ' },
    common: {
      search: 'ਖੋਜੋ',
      call: 'ਕਾਲ',
      directions: 'ਦਿਸ਼ਾਵਾਂ',
      verified: 'ਤਸਦੀਕਸ਼ੁਦਾ',
      save: 'ਸੇਵ',
      saved: 'ਸੇਵ ਕੀਤਾ',
      all: 'ਸਭ',
      signIn: 'ਸਾਈਨ ਇਨ',
      signOut: 'ਸਾਈਨ ਆਉਟ',
      username: 'ਯੂਜ਼ਰਨੇਮ',
      password: 'ਪਾਸਵਰਡ',
      close: 'ਬੰਦ',
    },
    home: {
      heroKicker: 'ਸਿਲਿਗੁੜੀ ਵਿੱਚ ਸ਼ੁਰੂਆਤ',
      heroTitle: 'ਦੇਖਭਾਲ, ਸੇਵਾਵਾਂ ਅਤੇ ਫਾਲੋ-ਅੱਪ ਲਈ ਇੱਕ ਸਾਥੀ ਪਰਤ।',
      heroBody: 'ਤਸਦੀਕਸ਼ੁਦਾ ਸਥਾਨਕ ਪ੍ਰਦਾਤਾਵਾਂ ਨਾਲ ਸ਼ੁਰੂ ਕਰੋ, ਟਾਈਪ ਕਰਨ ਦੀ ਥਾਂ ਕਾਲ ਕਰੋ, ਸਬੂਤ ਸੇਵ ਕਰੋ ਅਤੇ ਦੂਰ ਬੈਠੇ ਪਰਿਵਾਰ ਨੂੰ ਲੂਪ ਵਿੱਚ ਰੱਖੋ।',
      heroPrimary: 'ਤਸਦੀਕਸ਼ੁਦਾ ਮਦਦ ਲੱਭੋ',
      heroSecondary: 'ਕਾਲਬੈਕ ਮੰਗੋ',
      signalCity: 'ਲਾਂਚ ਸ਼ਹਿਰ: ਸਿਲਿਗੁੜੀ',
      signalVerified: 'ਸਰੋਤ-ਲਿੰਕਡ',
      signalCaregiver: 'ਕੇਅਰਗਿਵਰ-ਤਿਆਰ',
      mobileNeedTitle: 'ਅੱਜ ਤੁਹਾਨੂੰ ਕੀ ਚਾਹੀਦਾ ਹੈ?',
      mobileServiceTitle: 'ਦੇਖਭਾਲ ਲੱਭੋ',
      mobileServiceBody: 'ਡਾਕਟਰ, ਸਫ਼ਰ ਅਤੇ ਬਜ਼ੁਰਗਾਂ ਦੀ ਮਦਦ।',
      mobileCommunityTitle: 'ਸਥਾਨਕਾਂ ਨੂੰ ਪੁੱਛੋ',
      mobileCommunityBody: 'ਨੇੜਲੇ ਸਿਲਿਗੁੜੀ ਪਰਿਵਾਰਾਂ ਨੂੰ ਪੁੱਛੋ।',
      mobileHelpTitle: 'ਤੁਰੰਤ ਮਦਦ ਚਾਹੀਦੀ ਹੈ?',
      mobileHelpBody: 'Saathi ਹੈਲਪ ਡੈਸਕ ਤੋਂ ਕਾਲ ਜਾਂ ਕਾਲਬੈਕ ਮੰਗੋ।',
      browseCategories: 'ਸ਼੍ਰੇਣੀਆਂ ਵੇਖੋ',
      topRated: 'ਤੁਹਾਡੇ ਨੇੜੇ ਚੋਟੀ ਦੇ ਰੇਟਡ',
      seeAll: 'ਸਭ ਵੇਖੋ',
      scaleTitle: 'ਸਿਲਿਗੁੜੀ ਪਹਿਲਾ ਸਬੂਤ ਹੈ, ਹੱਦ ਨਹੀਂ',
      scaleBody: 'ਇੰਟਰਫੇਸ ਸ਼ਹਿਰ-ਸਮਝਦਾਰ ਹੈ, ਇਸ ਲਈ ਇਹੀ ਭਰੋਸੇ ਵਾਲਾ ਸਿਸਟਮ ਸਥਾਨਕ ਸੰਦਰਭ ਗੁਆਏ ਬਿਨਾਂ ਹੋਰ ਭਾਰਤੀ ਸ਼ਹਿਰਾਂ ਤੱਕ ਵਧ ਸਕਦਾ ਹੈ।',
      myCalendar: 'ਮੇਰਾ ਕੈਲੰਡਰ',
      connectors: 'ਕਨੈਕਸ਼ਨ',
      connectorsCaption: 'ਵੇਖੋ Saathi ਕੀ ਜੋੜ ਸਕਦਾ ਹੈ',
    },
    categories: {
      elder_home: 'ਬਜ਼ੁਰਗ ਦੇਖਭਾਲ ਅਤੇ ਘਰ',
      doctor: 'ਡਾਕਟਰ',
      hospital: 'ਹਸਪਤਾਲ',
      medical_shop: 'ਮੈਡੀਕਲ ਦੁਕਾਨਾਂ',
      travel_agent: 'ਯਾਤਰਾ ਅਤੇ ਆਵਾਜਾਈ',
      daily_service: 'ਰੋਜ਼ਾਨਾ ਅਤੇ ਨਾਗਰਿਕ ਮਦਦ',
    },
    services: {
      title: 'ਸੇਵਾਵਾਂ',
      searchPlaceholder: 'Saathi ਦੀਆਂ ਲਿਸਟ ਕੀਤੀਆਂ ਸੇਵਾਵਾਂ ਖੋਜੋ...',
      favorites: 'ਮਨਪਸੰਦ',
      recentlyViewed: 'ਹਾਲ ਹੀ ਵਿੱਚ ਵੇਖਿਆ',
      trustChecklist: 'ਭਰੋਸਾ ਚੈਕਲਿਸਟ',
      sourceLinked: 'ਸਰੋਤ ਲਿੰਕ',
      callFirst: 'ਜਾਣ ਤੋਂ ਪਹਿਲਾਂ ਕਾਲ ਕਰੋ',
      viewSource: 'ਸਰੋਤ ਵੇਖੋ',
      contactActions: 'ਸੰਪਰਕ ਕਾਰਵਾਈਆਂ',
    },
    help: { title: '24/7 ਹੈਲਪਲਾਈਨ', callNow: 'ਹੁਣ ਹੈਲਪਲਾਈਨ ਤੇ ਕਾਲ ਕਰੋ', requestCallback: 'ਕਾਲਬੈਕ ਮੰਗੋ', languages: 'ਹਿੰਦੀ ਅਤੇ ਅੰਗਰੇਜ਼ੀ ਵਿੱਚ ਉਪਲਬਧ' },
    auth: {
      welcome: 'Saathi ਵਿੱਚ ਸੁਆਗਤ ਹੈ',
      signInOnly: 'ਆਪਣੇ ਖਾਤੇ ਵਿੱਚ ਸਾਈਨ ਇਨ ਕਰੋ',
      createAccountOnly: 'ਆਪਣਾ ਖਾਤਾ ਬਣਾਓ',
      fullName: 'ਪੂਰਾ ਨਾਮ',
      identifier: 'ਯੂਜ਼ਰਨੇਮ ਜਾਂ ਫੋਨ ਨੰਬਰ',
      identifierPlaceholder: 'Aadit_J ਜਾਂ +91 98765 43210',
      createAccount: 'ਖਾਤਾ ਬਣਾਓ',
      haveAccount: 'ਮੇਰਾ ਪਹਿਲਾਂ ਹੀ ਖਾਤਾ ਹੈ',
      needAccount: 'ਨਵਾਂ ਖਾਤਾ ਬਣਾਓ',
    },
  },
  ta: {
    tabs: { home: 'முகப்பு', services: 'சேவைகள்', assistant: 'உதவியாளர்', community: 'சமூகம்', help: 'உதவி' },
    common: {
      search: 'தேடு',
      call: 'அழை',
      directions: 'வழிகள்',
      verified: 'சரிபார்க்கப்பட்டது',
      save: 'சேமி',
      saved: 'சேமிக்கப்பட்டது',
      all: 'அனைத்தும்',
      signIn: 'உள்நுழை',
      signOut: 'வெளியேறு',
      username: 'பயனர் பெயர்',
      password: 'கடவுச்சொல்',
      close: 'மூடு',
    },
    home: {
      heroKicker: 'சிலிகுரியில் தொடக்கம்',
      heroTitle: 'பராமரிப்பு, சேவைகள் மற்றும் பின்தொடர்வுக்கு ஒரு துணை அடுக்கு.',
      heroBody: 'சரிபார்க்கப்பட்ட உள்ளூர் வழங்குநர்களுடன் தொடங்குங்கள், டைப் செய்வதற்குப் பதில் அழையுங்கள், ஆதாரத்தை சேமியுங்கள், தூரத்தில் உள்ள குடும்பத்தையும் இணைத்திருங்கள்.',
      heroPrimary: 'சரிபார்க்கப்பட்ட உதவி தேடு',
      heroSecondary: 'கால்பேக் கேள்',
      signalCity: 'தொடக்க நகரம்: சிலிகுரி',
      signalVerified: 'மூல-இணைப்பு',
      signalCaregiver: 'பராமரிப்பாளர்-தயார்',
      mobileNeedTitle: 'இன்று உங்களுக்கு என்ன தேவை?',
      mobileServiceTitle: 'பராமரிப்பு தேடு',
      mobileServiceBody: 'மருத்துவர், பயணம் மற்றும் முதியோர் உதவி.',
      mobileCommunityTitle: 'உள்ளூர்வாசிகளிடம் கேளுங்கள்',
      mobileCommunityBody: 'அருகிலுள்ள சிலிகுரி குடும்பங்களிடம் கேளுங்கள்.',
      mobileHelpTitle: 'அவசர உதவி வேண்டுமா?',
      mobileHelpBody: 'Saathi உதவி மேசையிலிருந்து அழைப்பு அல்லது கால்பேக் கேளுங்கள்.',
      browseCategories: 'வகைகள் பார்க்க',
      topRated: 'உங்கள் அருகில் சிறந்த மதிப்பீடு',
      seeAll: 'அனைத்தும் பார்க்க',
      scaleTitle: 'சிலிகுரி முதல் ஆதாரம், எல்லை அல்ல',
      scaleBody: 'இடைமுகம் நகரை கருத்தில் கொள்கிறது; அதே நம்பிக்கை அமைப்பு உள்ளூர் சூழலை இழக்காமல் பிற நகரங்களுக்கு விரிவடையலாம்.',
      myCalendar: 'என் காலண்டர்',
      connectors: 'இணைப்புகள்',
      connectorsCaption: 'Saathi என்ன இணைக்க முடியும் பாருங்கள்',
    },
    categories: {
      elder_home: 'முதியோர் பராமரிப்பு & இல்லங்கள்',
      doctor: 'மருத்துவர்கள்',
      hospital: 'மருத்துவமனைகள்',
      medical_shop: 'மருந்துக் கடைகள்',
      travel_agent: 'பயணம் & போக்குவரத்து',
      daily_service: 'தினசரி & குடிமை உதவி',
    },
    services: {
      title: 'சேவைகள்',
      searchPlaceholder: 'Saathi பட்டியலிட்ட சேவைகளை தேடுங்கள்...',
      favorites: 'பிடித்தவை',
      recentlyViewed: 'சமீபத்தில் பார்த்தவை',
      trustChecklist: 'நம்பிக்கை சரிபார்ப்பு',
      sourceLinked: 'மூல இணைப்பு',
      callFirst: 'செல்வதற்கு முன் அழைக்கவும்',
      viewSource: 'மூலம் பார்க்க',
      contactActions: 'தொடர்பு செயல்கள்',
    },
    help: { title: '24/7 உதவி எண்', callNow: 'இப்போது உதவி எண்ணை அழைக்கவும்', requestCallback: 'கால்பேக் கேள்', languages: 'இந்தி & ஆங்கிலத்தில் கிடைக்கும்' },
    auth: {
      welcome: 'Saathiக்கு வரவேற்கிறோம்',
      signInOnly: 'உங்கள் கணக்கில் உள்நுழையவும்',
      createAccountOnly: 'உங்கள் கணக்கை உருவாக்கவும்',
      fullName: 'முழுப் பெயர்',
      identifier: 'பயனர் பெயர் அல்லது தொலைபேசி எண்',
      identifierPlaceholder: 'Aadit_J அல்லது +91 98765 43210',
      createAccount: 'கணக்கு உருவாக்கு',
      haveAccount: 'எனக்கு ஏற்கனவே கணக்கு உள்ளது',
      needAccount: 'புதிய கணக்கு உருவாக்கு',
    },
  },
  te: {
    tabs: { home: 'హోమ్', services: 'సేవలు', assistant: 'సహాయకుడు', community: 'సమాజం', help: 'సహాయం' },
    common: {
      search: 'శోధించండి',
      call: 'కాల్',
      directions: 'దిశలు',
      verified: 'ధృవీకరించబడింది',
      save: 'సేవ్',
      saved: 'సేవ్ అయింది',
      all: 'అన్నీ',
      signIn: 'సైన్ ఇన్',
      signOut: 'సైన్ అవుట్',
      username: 'యూజర్‌నేమ్',
      password: 'పాస్‌వర్డ్',
      close: 'మూసివేయి',
    },
    home: {
      heroKicker: 'సిలిగురిలో ప్రారంభం',
      heroTitle: 'కేర్, సేవలు మరియు ఫాలో-అప్ కోసం ఒక తోడు పొర.',
      heroBody: 'ధృవీకరించిన స్థానిక ప్రొవైడర్లతో ప్రారంభించండి, టైప్ చేయడానికి బదులుగా కాల్ చేయండి, ఆధారాన్ని సేవ్ చేయండి మరియు దూరంలోని కుటుంబాన్ని లూప్‌లో ఉంచండి.',
      heroPrimary: 'ధృవీకరించిన సహాయం కనుగొనండి',
      heroSecondary: 'కాల్‌బ్యాక్ అడగండి',
      signalCity: 'లాంచ్ నగరం: సిలిగురి',
      signalVerified: 'మూలం-లింక్',
      signalCaregiver: 'కేర్‌గివర్-రెడీ',
      mobileNeedTitle: 'ఈ రోజు మీకు ఏమి కావాలి?',
      mobileServiceTitle: 'కేర్ కనుగొనండి',
      mobileServiceBody: 'డాక్టర్లు, ప్రయాణం మరియు వృద్ధుల సహాయం.',
      mobileCommunityTitle: 'స్థానికులను అడగండి',
      mobileCommunityBody: 'దగ్గరలోని సిలిగురి కుటుంబాలను అడగండి.',
      mobileHelpTitle: 'తక్షణ సహాయం కావాలా?',
      mobileHelpBody: 'Saathi హెల్ప్ డెస్క్ నుండి కాల్ లేదా కాల్‌బ్యాక్ అడగండి.',
      browseCategories: 'వర్గాలు చూడండి',
      topRated: 'మీ దగ్గర టాప్ రేటెడ్',
      seeAll: 'అన్నీ చూడండి',
      scaleTitle: 'సిలిగురి మొదటి సాక్ష్యం, సరిహద్దు కాదు',
      scaleBody: 'ఇంటర్‌ఫేస్ నగరాన్ని గుర్తుంచుకుంటుంది, కాబట్టి ఇదే నమ్మక వ్యవస్థ స్థానిక సందర్భం కోల్పోకుండా ఇతర నగరాలకు విస్తరించవచ్చు.',
      myCalendar: 'నా క్యాలెండర్',
      connectors: 'కనెక్షన్లు',
      connectorsCaption: 'Saathi ఏమి కనెక్ట్ చేయగలదో చూడండి',
    },
    categories: {
      elder_home: 'వృద్ధుల కేర్ & హోమ్స్',
      doctor: 'డాక్టర్లు',
      hospital: 'హాస్పిటళ్లు',
      medical_shop: 'మెడికల్ షాపులు',
      travel_agent: 'ప్రయాణం & రవాణా',
      daily_service: 'రోజువారీ & పౌర సహాయం',
    },
    services: {
      title: 'సేవలు',
      searchPlaceholder: 'Saathi లిస్టెడ్ సేవలను శోధించండి...',
      favorites: 'ఇష్టమైనవి',
      recentlyViewed: 'ఇటీవల చూసినవి',
      trustChecklist: 'నమ్మక చెక్‌లిస్ట్',
      sourceLinked: 'మూల లింక్',
      callFirst: 'వెళ్లే ముందు కాల్ చేయండి',
      viewSource: 'మూలం చూడండి',
      contactActions: 'సంప్రదింపు చర్యలు',
    },
    help: { title: '24/7 హెల్ప్‌లైన్', callNow: 'ఇప్పుడు హెల్ప్‌లైన్‌కు కాల్ చేయండి', requestCallback: 'కాల్‌బ్యాక్ అడగండి', languages: 'హిందీ & ఇంగ్లీష్‌లో అందుబాటులో ఉంది' },
    auth: {
      welcome: 'Saathiకి స్వాగతం',
      signInOnly: 'మీ ఖాతాలో సైన్ ఇన్ చేయండి',
      createAccountOnly: 'మీ ఖాతాను సృష్టించండి',
      fullName: 'పూర్తి పేరు',
      identifier: 'యూజర్‌నేమ్ లేదా ఫోన్ నంబర్',
      identifierPlaceholder: 'Aadit_J లేదా +91 98765 43210',
      createAccount: 'ఖాతా సృష్టించండి',
      haveAccount: 'నాకు ఇప్పటికే ఖాతా ఉంది',
      needAccount: 'కొత్త ఖాతా సృష్టించండి',
    },
  },
  ur: {
    tabs: { home: 'ہوم', services: 'خدمات', assistant: 'معاون', community: 'کمیونٹی', help: 'مدد' },
    common: {
      search: 'تلاش',
      call: 'کال',
      directions: 'راستہ',
      verified: 'تصدیق شدہ',
      save: 'محفوظ کریں',
      saved: 'محفوظ',
      all: 'سب',
      signIn: 'سائن ان',
      signOut: 'سائن آؤٹ',
      username: 'یوزرنیم',
      password: 'پاس ورڈ',
      close: 'بند',
    },
    home: {
      heroKicker: 'سلیگڑی میں آغاز',
      heroTitle: 'دیکھ بھال، خدمات اور فالو اپ کے لیے ایک ساتھی پرت۔',
      heroBody: 'تصدیق شدہ مقامی فراہم کنندگان سے شروع کریں، ٹائپ کرنے کے بجائے کال کریں، ثبوت محفوظ کریں اور دور موجود خاندان کو ساتھ رکھیں۔',
      heroPrimary: 'تصدیق شدہ مدد تلاش کریں',
      heroSecondary: 'کال بیک مانگیں',
      signalCity: 'لانچ شہر: سلیگڑی',
      signalVerified: 'ماخذ سے منسلک',
      signalCaregiver: 'کیئر گیور کے لیے تیار',
      mobileNeedTitle: 'آج آپ کو کیا چاہیے؟',
      mobileServiceTitle: 'دیکھ بھال تلاش کریں',
      mobileServiceBody: 'ڈاکٹر، سفر اور بزرگوں کی مدد۔',
      mobileCommunityTitle: 'مقامی لوگوں سے پوچھیں',
      mobileCommunityBody: 'قریبی سلیگڑی خاندانوں سے پوچھیں۔',
      mobileHelpTitle: 'فوری مدد چاہیے؟',
      mobileHelpBody: 'Saathi ہیلپ ڈیسک سے کال یا کال بیک مانگیں۔',
      browseCategories: 'زمرے دیکھیں',
      topRated: 'آپ کے قریب بہترین ریٹڈ',
      seeAll: 'سب دیکھیں',
      scaleTitle: 'سلیگڑی پہلا ثبوت ہے، حد نہیں',
      scaleBody: 'انٹرفیس شہر کو سمجھتا ہے، اس لیے یہی اعتماد کا نظام مقامی سیاق کھوئے بغیر دوسرے شہروں تک بڑھ سکتا ہے۔',
      myCalendar: 'میرا کیلنڈر',
      connectors: 'کنیکشنز',
      connectorsCaption: 'دیکھیں Saathi کیا جوڑ سکتا ہے',
    },
    categories: {
      elder_home: 'بزرگوں کی دیکھ بھال اور گھر',
      doctor: 'ڈاکٹر',
      hospital: 'اسپتال',
      medical_shop: 'میڈیکل شاپس',
      travel_agent: 'سفر اور ٹرانسپورٹ',
      daily_service: 'روزمرہ اور شہری مدد',
    },
    services: {
      title: 'خدمات',
      searchPlaceholder: 'Saathi کی درج خدمات تلاش کریں...',
      favorites: 'پسندیدہ',
      recentlyViewed: 'حال ہی میں دیکھا',
      trustChecklist: 'اعتماد چیک لسٹ',
      sourceLinked: 'ماخذ لنک',
      callFirst: 'جانے سے پہلے کال کریں',
      viewSource: 'ماخذ دیکھیں',
      contactActions: 'رابطہ کارروائیاں',
    },
    help: { title: '24/7 ہیلپ لائن', callNow: 'ابھی ہیلپ لائن پر کال کریں', requestCallback: 'کال بیک مانگیں', languages: 'ہندی اور انگریزی میں دستیاب' },
    auth: {
      welcome: 'Saathi میں خوش آمدید',
      signInOnly: 'اپنے اکاؤنٹ میں سائن ان کریں',
      createAccountOnly: 'اپنا اکاؤنٹ بنائیں',
      fullName: 'پورا نام',
      identifier: 'یوزرنیم یا فون نمبر',
      identifierPlaceholder: 'Aadit_J یا +91 98765 43210',
      createAccount: 'اکاؤنٹ بنائیں',
      haveAccount: 'میرا پہلے سے اکاؤنٹ ہے',
      needAccount: 'نیا اکاؤنٹ بنائیں',
    },
  },
};
