import type { RefObject } from 'react';
import gsap from 'gsap';
import { useGSAP } from '@gsap/react';

gsap.registerPlugin(useGSAP);

/**
 * Entrance timeline for one onboarding step.
 *
 * Targets are marked in JSX with `dataSet={{ anim: '…' }}`, which react-native-web
 * emits as a real `data-anim` attribute — the only way to hand GSAP a stable
 * selector when the markup is generated by RN primitives rather than written as
 * HTML. Selectors stay scoped to the screen root so a stray `[data-anim]`
 * elsewhere in the app can never be caught by this timeline.
 *
 * `stepKey` changes on every step, and `revertOnUpdate` reverts the previous
 * timeline before the next one builds. Without it the `.from()` tweens would
 * stack their inline styles and later steps would fade in from whatever the
 * earlier step happened to leave behind.
 */
export function useIntroAnimation(scope: RefObject<unknown>, stepKey: string): void {
  useGSAP(
    () => {
      const media = gsap.matchMedia();

      media.add(
        {
          full: '(prefers-reduced-motion: no-preference)',
          reduced: '(prefers-reduced-motion: reduce)',
        },
        (context) => {
          const { reduced } = context.conditions as { full: boolean; reduced: boolean };
          const badge = gsap.utils.toArray<HTMLElement>('[data-anim="badge"]');
          const items = gsap.utils.toArray<HTMLElement>('[data-anim="item"]');
          const footer = gsap.utils.toArray<HTMLElement>('[data-anim="footer"]');

          // Reduced motion still gets the step change, just without travel:
          // an elder who turned motion off should not be left staring at a
          // screen that never resolves.
          if (reduced) {
            gsap.from([...badge, ...items, ...footer], { opacity: 0, duration: 0.2 });
            return;
          }

          const timeline = gsap.timeline({ defaults: { ease: 'power4.out' } });

          timeline
            .from(badge, {
              opacity: 0,
              scale: 0.7,
              y: 14,
              rotate: -8,
              duration: 0.62,
              ease: 'back.out(1.7)',
            })
            .from(items, { opacity: 0, y: 22, duration: 0.55, stagger: 0.08 }, '-=0.38')
            .from(footer, { opacity: 0, y: 16, duration: 0.45 }, '-=0.32');
        },
      );

      return () => media.revert();
    },
    { dependencies: [stepKey], scope: scope as RefObject<HTMLElement>, revertOnUpdate: true },
  );
}
